### ISSUE TITLE
your repo myrepo is empty, why myrepo is empty and why your repo name as myrepo it shouldn't be myrepo it gets confusing to tell whether it is your repo or myrepo

### ISSUE THREAD

**Issue by Tushargupta9800** [utkarshgarg123/myrepo#1]

**Comment by Tushargupta9800** [comment]
my repo is my repo none of your repo and your repo is myrepo

**Comment by utkarshgarg123** [comment]
> my repo is my repo none of your repo and your repo is myrepo

![IMG_20201216_232619.jpg](https://user-images.githubusercontent.com/54159419/102387249-275f6500-3ff6-11eb-97b2-d980913e730e.jpg)

**Comment by Tushargupta9800** [comment]
my repo is not your repo your repo is my repo
